title: Carlos Pelaez
#logo: /assets/img/headshot_circle.png
description: Showcase of my Data Engineering projects, skills, and experience.
show_downloads:  False
theme: jekyll-theme-minimal
#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

